@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(container2, "", "")
Container(container3, "", "")
Person(person, "", "")
System(system1, "", "")
System(system2, "", "")
System(system3, "", "")
Container(container1, "", "")

Rel(person, system1, "", "")
Rel(system1, system2, "", "")
Rel(system1, system3, "", "")
Rel(system2, container1, "", "")
Rel(system2, container2, "", "")
Rel(system3, container3, "", "")

@enduml
